config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'chatroom#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  post 'message', to: 'messages#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
    validates :body, presence: true
    scope :custom_display, -> { order(:created_at).last(25)}
    # Ex:- scope :active, -> {where(:active => true)}
end

app/models/user.rb
class User < ApplicationRecord
    validates :username, presence: true, length: {minimum:3, maximum:25}, 
              uniqueness: { case_sensitive: false }
    has_secure_password
    has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :logged_in?, :current_user

    def logged_in?
        !!current_user
    end
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    def require_user
        if !logged_in?
            flash[:error] = "You must login first"
            redirect_to login_path
        end
    end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
    before_action :require_user
    def index
        @message = Message.new
        @messages = Message.custom_display
    end    
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :require_user
    def create
        @message = current_user.messages.build(message_params)
        if @message.save
            ActionCable.server.broadcast "chatroom_channel", {user_message: message_render(@message)}
        end
    end
    private
    def message_params
        params.require(:message).permit(:body)
    end
    def message_render(message)
        render(partial: 'message', locals: {message: message})
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :logged_in_redirect, only: [:new, :create]

    def new
    end
    def create
        @user = User.find_by(username: params[:session][:username])
        if @user && @user.authenticate(params[:session][:password])
            session[:user_id] = @user.id
            flash[:success] = "You are logged in sucessfully"
            redirect_to root_path
        else
            flash.now[:error] = "You entered wrong credentials"
            render 'new'
        end   
    end
    def destroy
        session[:user_id] = nil
        flash[:success] = "You have logged out sucessfully"
        redirect_to login_path
    end
    private 
    def logged_in_redirect
        if logged_in?
            flash[:error] = "You are aleardy logged in !"
            redirect_to root_path
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :logged_in_redirect, only: [:new, :create]

    def new
        @user = User.new
    end
    def create
        @user = User.new(username: params[:user][:username], password: params[:user][:password])
        if @user.save
            session[:user_id] = @user.id
            flash[:success] = "You are logged in sucessfully"
            redirect_to root_path
        else
            render 'new'
        end   
    end
    private 
    def logged_in_redirect
        if logged_in?
            flash[:error] = "You are aleardy logged in !"
            redirect_to root_path
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<h4 class="ui center aligned medium icon header">
    <i class="circular blue chat icon"></i>
    Say Hello!
</h4>

<div class="ui two column grid">
   <div class="ui four wide column">
        <div class="ui fluid raised card" style="height: 450px;">
            <div class="content">
                <div class="ui blue vertical pointing menu" style="width: auto;" id="online-users">
                    <a class="item" >
                        Messages
                    </a>
                </div>   
            </div>
        </div>
    </div>
    <div class="ui twelve wide column">
        <div class="ui fluid raised card" style="height: 450px;">
            <div class="content" style="overflow: auto; height: 16em" id="messages">
                <div class="ui feed" id="message-box">
                    <%= render @messages%>
                </div>
            </div>
            <div class="extra content">
                <%= form_for(@message, html: {class: "ui reply form"}, role: "form", url: message_path, remote: true) do |f|%>
                    <div class="field">
                        <div class="ui fluid blue icon input">
                        <%= f.text_field :body,  placeholder: "Enter your message..."%>
                         <%= f.button '<i class="bordered blue inverted icon edit" id="send-chat"></i>'.html_safe%>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |type, msg| %>
    <div class="ui <%="#{type}" %> message transition">
        <i class="close icon"></i>
        <div class="header">
            <%= msg %>
        </div>
    </div>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="ui small inverted menu">
    <div class="ui container">
        <%= link_to "Chatroom", root_path, class: "item"%>
        <div class="right menu">
            <div class="ui dropdown item">
            Account <i class="dropdown icon"></i>
            <div class="menu">
                <% if logged_in? %>
                    <%= link_to "Log out", logout_path, method: :delete, class: "item"%>
                <% else %>
                    <%= link_to "Sign up", signup_path, class: "item"%>
                    <%= link_to "Log in", login_path, class: "item"%>
                <% end %>
            </div>
            </div>
            <div class="item">
                <% if !logged_in? %>
                    <%= link_to "Log in", login_path, class: "ui primary button"%>
                <% end %>
            </div>
            <div class="item">
                <% if !logged_in? %>
                    <%= link_to "Sign up", signup_path, class: "ui primary button"%>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageApp</title>
    <%= favicon_link_tag%>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
  <div class="ui container">
    <%= render 'layouts/messages'%>
    <%= yield %>
  </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
    <div class="content">
        <div class="summary">
            <em><%= message.user.username %></em>: <%= message.body %>
        </div>
    </div>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="ui error message transition">
        <i class="close icon"></i>
        <div class="header">
            <h2><%= pluralize(object.errors.count, "Error") %> The following error prevent the user from being saved:</h2>
            <ul>
              <% object.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
        </div>
    </div>
<% end %>

app/views/users/new.html.erb
<%= render 'shared/errors', object: @user %>
<h1 align="center">Welcome to the Real Time message application</h1>
<h4 class="ui center aligned medium icon header">
    <i class="circular blue chat icon"></i>
    Sign Up to start chatting
</h4>
<div class="center">
    <div class="ui placeholder segment">
        <div class="ui two column very relaxed stackable grid center-signup">
            <div class="column">
                <%= form_for(:user, html: {class: "ui form", role: "form"}, url: signup_path) do |f|%>
                    <div class="field">
                        <%= f.label :username, "Username", style: "display: flex;justify-content: center;"%>
                        <div class="ui left icon input">
                            <%= f.text_field :username, placeholder: "Username"%>
                            <i class="user icon"></i>
                        </div>
                    </div>
                    <div class="field">
                        <%= f.label :password, "Password", style: "display: flex;justify-content: center;"%>
                        <div class="ui left icon input">
                            <%= f.password_field :password, placeholder: "Password"%>
                            <i class="lock icon"></i>
                        </div>
                    </div>
                    <%= f.submit "Login", class: "ui blue submit button" %> 
                <% end %>
            </div>
        </div>
    </div>
</div>